routes/web.php
<?php

use App\Http\Controllers\Announcements\AnnouncementController;
use App\Http\Controllers\Auth\AuthController;
use App\Http\Controllers\Books\BookController;
use App\Http\Controllers\Categories\CategoryController;
use App\Http\Controllers\Electrons\ElectronController;
use App\Http\Controllers\Genres\GenreController;
use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Route::get('/', [AuthController::class, 'login'])->name('login');
Route::post('/login', [AuthController::class, 'auth'])->name('auth.login');
Route::get('/logout', [AuthController::class, 'logout'])->name('auth.logout');

//---------------------------------------------------------------  ADMIN START -------------------------------------------------------------------------------------------------
Route::group(['prefix' => 'dashboard', 'middleware' => ['auth:sanctum']], function () {
    Route::get('index', [HomeController::class, 'index'])->name('admin.home');
    Route::resource('categories', CategoryController::class);
    Route::resource('genres', GenreController::class);
    Route::resource('books', BookController::class);
    Route::resource('electrons', ElectronController::class);
    Route::resource('announcements', AnnouncementController::class);
});
//---------------------------------------------------------------  ADMIN END -----------------------------------------------------------------------------------------------------

app/Http/Controllers/Genres/GenreController.php
<?php

namespace App\Http\Controllers\Genres;

use App\Domain\Genres\Actions\StoreGenreAction;
use App\Domain\Genres\Actions\UpdateGenreAction;
use App\Domain\Genres\DTO\StoreGenreDTO;
use App\Domain\Genres\DTO\UpdateGenreDTO;
use App\Domain\Genres\Repositories\GenreRepository;
use App\Domain\Genres\Requests\StoreGenreRequest;
use App\Domain\Genres\Requests\UpdateGenreRequest;
use App\Domain\Genres\Models\Genre;
use App\Http\Controllers\Controller;
use Exception;
use Illuminate\Http\Request;

class GenreController extends Controller
{
    /**
     * @var mixed|GenreRepository
     */
    public mixed $genres;

    /**
     * @param GenreRepository $genreRepository
     */
    public function __construct(GenreRepository $genreRepository)
    {
        $this->genres = $genreRepository;
    }

    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        return view('dashboard.genres.index', [
            'genres' => $this->genres->paginate()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('dashboard.genres.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreGenreRequest $request, StoreGenreAction $action)
    {
        $request->validated();
        try {
            $dto = StoreGenreDTO::fromArray($request->all());
            $action->execute($dto);
        } catch (Exception $exception) {
            return redirect()->back();
        }

        return redirect()->route('genres.index');
    }

    /**
     * Display the specified resource.
     */
    public function show(Genre $genre)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Genre $genre)
    {
        return view('dashboard.genres.edit', [
            'genre' => $genre
        ]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateGenreRequest $request, Genre $genre, UpdateGenreAction $action)
    {
        $request->merge([
            'genre' => $genre
        ]);
        $request->validated();
        try {
            $dto = UpdateGenreDTO::fromArray($request->all());
            $action->execute($dto);
        } catch (Exception $exception) {
            return redirect()->back();
        }

        return redirect()->route('genres.index');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Genre $genre)
    {
        $genre->delete();
        return redirect()->back();
    }
}

resources/views/dashboard/genres/create.blade.php
@extends('dashboard.layouts.master')
@section('content')
    <div class="card">
        <form action="{{ route('genres.store') }}" method="post" enctype="multipart/form-data">
            @csrf
            <div class="card-header">
                <h5 class="mb-0">Janr qo'shish</h5>
                @if ($errors->any())
                    @foreach ($errors->all() as $error)
                        <div class="alert alert-danger">{{$error}}</div>
                    @endforeach
                @endif
            </div>

            <div class="card-body row">
                <div class="mb-3 col-md-12">
                    <label for="name" class="form-label">Janr nomi</label>
                    <input type="text" value="{{ old('name') }}" id="name" class="form-control" name="name" placeholder="Janr nomi">
                </div>
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary w-100">Saqlash <i class="ph-paper-plane-tilt ms-2"></i>
                </button>
            </div>
        </form>
    </div>
@endsection

resources/views/dashboard/genres/edit.blade.php
@extends('dashboard.layouts.master')
@section('content')
    <div class="card">
        <form action="{{ route('genres.update',$genre) }}" method="post" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="card-header">
                <h5 class="mb-0">Janrni tahrirlash</h5>
                @if ($errors->any())
                    @foreach ($errors->all() as $error)
                        <div class="alert alert-danger">{{$error}}</div>
                    @endforeach
                @endif
            </div>

            <div class="card-body row">
                <div class="mb-3 col-md-12">
                    <label for="name" class="form-label">Janr nomi</label>
                    <input type="text" value="{{ $genre->name }}" id="name" class="form-control" name="name"
                           placeholder="Janr nomi">
                </div>
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary w-100">Saqlash <i class="ph-paper-plane-tilt ms-2"></i>
                </button>
            </div>
        </form>
    </div>
@endsection

resources/views/dashboard/genres/index.blade.php
@extends('dashboard.layouts.master')
@section('content')
    <div class="card">
        <div class="card-header d-flex align-content-center justify-content-between">
            <h5 class="mb-0">Janrlar ro'yxati</h5>
            <div>
                <a href="{{ route('genres.create') }}" class="btn btn-sm btn-success">Qo'shish</a>
                <button type="button" class="btn btn-primary btn-sm">Filter</button>
            </div>
        </div>

        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>№</th>
                        <th>Janr nomi</th>
                        <th>Harakat</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($genres as $genre)
                        <tr>
                            <td>{{ ($genres->currentPage()-1)*$genres->perPage() + $loop->index+1 }}</td>
                            <td>{{ $genre->name }}</td>
                            <td>
                                <div class="d-flex align-items-center">
                                    <a href="{{ route('genres.edit',$genre) }}" class="btn btn-sm btn-info" style="margin-right: 10px;"><i class="ph-pencil"></i></a>
                                    <form action="{{ route('genres.destroy',$genre) }}" method="post">
                                        @csrf
                                        @method('DELETE')
                                        <button onclick="return confirm('Siz ushbu janrni o\'chirmoqchimisiz?');" type="submit" class="btn btn-sm btn-danger"><i class="ph-trash"></i></button>
                                    </form>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>

        <div class="card-footer">
            {{ $genres->links() }}
        </div>
    </div>
@endsection