routes/web.php
<?php

use App\Http\Controllers\Announcements\AnnouncementController;
use App\Http\Controllers\Auth\AuthController;
use App\Http\Controllers\Books\BookController;
use App\Http\Controllers\Categories\CategoryController;
use App\Http\Controllers\Electrons\ElectronController;
use App\Http\Controllers\Genres\GenreController;
use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Route::get('/', [AuthController::class, 'login'])->name('login');
Route::post('/login', [AuthController::class, 'auth'])->name('auth.login');
Route::get('/logout', [AuthController::class, 'logout'])->name('auth.logout');

//---------------------------------------------------------------  ADMIN START -------------------------------------------------------------------------------------------------
Route::group(['prefix' => 'dashboard', 'middleware' => ['auth:sanctum']], function () {
    Route::get('index', [HomeController::class, 'index'])->name('admin.home');
    Route::resource('categories', CategoryController::class);
    Route::resource('genres', GenreController::class);
    Route::resource('books', BookController::class);
    Route::resource('electrons', ElectronController::class);
    Route::resource('announcements', AnnouncementController::class);
});
//---------------------------------------------------------------  ADMIN END -----------------------------------------------------------------------------------------------------

app/Http/Controllers/Books/BookController.php
<?php

namespace App\Http\Controllers\Books;

use App\Domain\Books\Actions\StoreBookAction;
use App\Domain\Books\Actions\UpdateBookAction;
use App\Domain\Books\DTO\StoreBookDTO;
use App\Domain\Books\DTO\UpdateBookDTO;
use App\Domain\Books\Repositories\BookRepository;
use App\Domain\Books\Requests\StoreBookRequest;
use App\Domain\Books\Requests\UpdateBookRequest;
use App\Domain\Categories\Repositories\CategoryRepository;
use App\Domain\Genres\Repositories\GenreRepository;
use App\Filters\BooksFilter;
use App\Http\Controllers\Controller;
use App\Domain\Books\Models\Book;
use App\Http\Requests\Filters\BookFilterRequest;
use App\Http\Resources\Api\Books\BookResource;
use Exception;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\AnonymousResourceCollection;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;

class BookController extends Controller
{
    /**
     * @var mixed|BookRepository
     */
    public mixed $books;

    /**
     * @var mixed|CategoryRepository
     */
    public mixed $categories;

    /**
     * @var mixed|GenreRepository
     */
    public mixed $genres;

    /**
     * @param BookRepository $bookRepository
     * @param CategoryRepository $categoryRepository
     * @param GenreRepository $genreRepository
     */
    public function __construct(BookRepository $bookRepository, CategoryRepository $categoryRepository, GenreRepository $genreRepository)
    {
        $this->books = $bookRepository;
        $this->categories = $categoryRepository;
        $this->genres = $genreRepository;
    }

    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        return view('dashboard.books.index', [
            'books' => $this->books->paginate()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('dashboard.books.create', [
            'categories' => $this->categories->getAll(),
            'genres' => $this->genres->getAll()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreBookRequest $request, StoreBookAction $action)
    {
        $request->validated();
        try {
            $dto = StoreBookDTO::fromArray($request->all());
            $action->execute($dto);
        } catch (Exception $exception) {
            return redirect()->back();
        }

        return redirect()->route('books.index');
    }

    /**
     * Display the specified resource.
     */
    public function show(Book $book)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Book $book)
    {
        return view('dashboard.books.edit', [
            'book' => $book,
            'categories' => $this->categories->getAll(),
            'genres' => $this->genres->getAll(),
            'selected_genres' => $book->genres->pluck('pivot.genre_id')->toArray()
        ]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateBookRequest $request, Book $book, UpdateBookAction $action)
    {
        $request->merge([
            'book' => $book
        ]);
        $request->validated();
        try {
            $dto = UpdateBookDTO::fromArray($request->all());
            $action->execute($dto);
        } catch (Exception $exception) {
            return redirect()->back();
        }

        return redirect()->route('books.index');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Book $book)
    {
        File::delete('storage/books/images/' . $book->image);
        File::delete('storage/books/files/' . $book->file);
        $book->delete();

        return redirect()->back();
    }


//------------------------------------------------------------------------  API  ---------------------------------------------------------------------------------------

    /**
     * @return AnonymousResourceCollection
     * @throws \Illuminate\Contracts\Container\BindingResolutionException
     */
    public function getAllBook(BookFilterRequest $request)
    {
        $filter = app()->make(BooksFilter::class, ['queryParams' => array_filter($request->validated())]);
        return BookResource::collection($this->books->getAllBookPaginate($filter));
    }

    /**
     * @return BookResource
     */
    public function showBook($book_id)
    {
        return new BookResource($this->books->showBook($book_id));
    }

    /**
     * @return AnonymousResourceCollection
     */
    public function showForCategoryAllBooks($category_id)
    {
        return BookResource::collection($this->books->showForCategoryAllBooks($category_id));
    }

//------------------------------------------------------------------------  API  ---------------------------------------------------------------------------------------
}

resources/views/dashboard/books/create.blade.php
@extends('dashboard.layouts.master')
@section('content')
    <div class="card">
        <form action="{{ route('books.store') }}" method="post" enctype="multipart/form-data">
            @csrf
            <div class="card-header">
                <h5 class="mb-0">Kitob qo'shish</h5>
                @if ($errors->any())
                    @foreach ($errors->all() as $error)
                        <div class="alert alert-danger">{{$error}}</div>
                    @endforeach
                @endif
            </div>

            <div class="card-body row">
                <div class="col-md-5 mb-3">
                    <label for="category_id" class="form-label">Kategoriya</label>
                    <select id="category_id" data-placeholder="Kategoriyani tanlang!" class="select form-control"
                            name="category_id">
                        <option selected value="">Kategoriyani tanlang!</option>
                        @foreach($categories as $category)
                            <option value="{{ $category->id }}">{{$category->name}}</option>
                        @endforeach
                    </select>
                </div>
                <div class="col-md-5">
                    <label for="genre_id" class="form-label">Janr</label>
                    <select id="genre_id" name="genre_id[]" multiple="multiple" class="select form-control"
                            data-select2-id="56" tabindex="-1" aria-hidden="true">
                        @foreach($genres as $genre)
                            <option value="{{ $genre->id }}">{{$genre->name}}</option>
                        @endforeach
                    </select>
                </div>
                <div class="col-md-2 mb-3">
                    <label for="author" class="form-label">Avtor F.I.O</label>
                    <input name="author" id="author" type="text" class="form-control" placeholder="Salimov Bekhruz">
                </div>
                <div class="mb-3 col-md-6">
                    <label for="title" class="form-label">Title</label>
                    <textarea class="form-control" rows="10" id="title" name="title"
                              placeholder="Title...">{{ old('title') }}</textarea>
                </div>
                <div class="mb-3 col-md-6">
                    <label for="description" class="form-label">Tavsif</label>
                    <textarea class="form-control" rows="10" id="description" name="description"
                              placeholder="Tavsif...">{{ old('description') }}</textarea>
                </div>

                <div class="col-md-6 mb-3">
                    <label for="image" class="form-label">Kitob rasmi <span class="text-danger fw-bold">(format:png, jpg, jpeg  max: 10MB)</span></label>
                    <input name="image" id="image" type="file" class="form-control">
                </div>
                <div class="col-md-6 mb-3">
                    <label for="file" class="form-label">Kitob fayli <span class="text-danger fw-bold">(format:pdf  max: 100MB)</span></label>
                    <input name="file" id="file" type="file" class="form-control">
                </div>
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary w-100">Saqlash <i class="ph-paper-plane-tilt ms-2"></i>
                </button>
            </div>
        </form>
    </div>
@endsection
@push('scripts')
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet"/>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script>
        $(document).ready(function () {
            $('.select').select2();
        });
    </script>
@endpush

resources/views/dashboard/books/edit.blade.php
@extends('dashboard.layouts.master')
@section('content')
    <div class="card">
        <form action="{{ route('books.update',$book) }}" method="post" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="card-header">
                <h5 class="mb-0">Kitobni tahrirlash</h5>
                @if ($errors->any())
                    @foreach ($errors->all() as $error)
                        <div class="alert alert-danger">{{$error}}</div>
                    @endforeach
                @endif
            </div>

            <div class="card-body row">
                <div class="col-md-5 mb-3">
                    <label for="category_id" class="form-label">Kategoriya</label>
                    <select id="category_id" data-placeholder="Kategoriyani tanlang!" class="select form-control"
                            name="category_id">
                        @foreach($categories as $category)
                            @if($category->id == $book->category_id)
                                <option selected value="{{ $category->id }}">{{$category->name}}</option>
                            @else
                                <option value="{{ $category->id }}">{{$category->name}}</option>
                            @endif
                        @endforeach
                    </select>
                </div>
                <div class="col-md-5">
                    <label for="genre_id" class="form-label">Janr</label>
                    <select id="genre_id" name="genre_id[]" multiple="multiple" class="select form-control"
                            data-select2-id="56" tabindex="-1" aria-hidden="true">
                        @foreach($genres as $genre)
                            @if(in_array($genre->id, $selected_genres))
                                <option selected data-select2-id="{{ $genre->id }}"
                                        value="{{ $genre->id }}">{{$genre->name}}</option>
                            @else
                                <option value="{{ $genre->id }}">{{$genre->name}}</option>
                            @endif
                        @endforeach
                    </select>
                </div>
                <div class="col-md-2 mb-3">
                    <label for="author" class="form-label">Avtor F.I.O</label>
                    <input value="{{ $book->author }}" name="author" id="author" type="text" class="form-control" placeholder="Salimov Bekhruz">
                </div>
                <div class="mb-3 col-md-6">
                    <label for="title" class="form-label">Title</label>
                    <textarea class="form-control" rows="10" id="title" name="title"
                              placeholder="Title...">{{ $book->title }}</textarea>
                </div>
                <div class="mb-3 col-md-6">
                    <label for="description" class="form-label">Tavsif</label>
                    <textarea class="form-control" rows="10" id="description" name="description"
                              placeholder="Tavsif...">{{ $book->description }}</textarea>
                </div>

                <div class="col-md-6 mb-3">
                    <label for="image" class="form-label">Kitob rasmi <span class="text-danger fw-bold">(format:png, jpg, jpeg  max: 10MB)</span></label>
                    <input style="margin-bottom: 10px;" name="image" id="image" type="file" class="form-control">
                    <img src="{{ asset('storage/books/images/'.$book->image) }}" style="margin-right: 10px;"
                         class="w-40px h-40px rounded-pill" alt="book image">
                </div>
                <div class="col-md-6 mb-3">
                    <label for="file" class="form-label">Kitob fayli <span class="text-danger fw-bold">(format:pdf  max: 100MB)</span></label>
                    <input style="margin-bottom: 10px;" name="file" id="file" type="file" class="form-control">
                    <a target="_blank" class="btn btn-sm btn-flat-info" style="margin-right: 10px;"
                       href="{{ asset('storage/books/files/'.$book->file) }}">
                        <i class="ph-book"></i>
                    </a>
                </div>
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary w-100">Saqlash <i class="ph-paper-plane-tilt ms-2"></i>
                </button>
            </div>
        </form>
    </div>
@endsection
@push('scripts')
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet"/>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script>
        $(document).ready(function () {
            $('.select').select2();
        });
    </script>
@endpush

resources/views/dashboard/books/index.blade.php
@extends('dashboard.layouts.master')
@section('content')
    <div class="card">
        <div class="card-header d-flex align-content-center justify-content-between">
            <h5 class="mb-0">Kitoblar ro'yxati</h5>
            <div>
                <a href="{{ route('books.create') }}" class="btn btn-sm btn-success">Qo'shish</a>
                <button type="button" class="btn btn-primary btn-sm">Filter</button>
            </div>
        </div>

        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>№</th>
                        <th>Author</th>
                        <th>Kategoriya</th>
                        <th>Janr</th>
                        <th>Title</th>
                        <th>Harakatlar</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($books as $book)
                        <tr>
                            <td>{{ ($books->currentPage()-1) * $books->perPage() + $loop->index+1 }}</td>
                            <td>{{ $book->author }}</td>
                            <td>{{ $book->category->name }}</td>
                            <td>
                                @foreach($book->genres as $genre)
                                    <span class="badge bg-success">{{ $genre->name }}</span>
                                @endforeach
                            </td>
                            <td>{{ \Illuminate\Support\Str::limit($book->title,50,"...") }}</td>
                            <td>
                                <div class="d-flex align-items-center">
                                    <img src="{{ asset('storage/books/images/'.$book->image) }}"
                                         style="margin-right: 10px;" class="w-40px h-40px rounded-pill"
                                         alt="book image">
                                    <a target="_blank" class="btn btn-sm btn-flat-info" style="margin-right: 10px;"
                                       href="{{ asset('storage/books/files/'.$book->file) }}">
                                        <i class="ph-book"></i>
                                    </a>
                                    <a href="{{ route('books.edit',$book) }}" class="btn btn-sm btn-info"
                                       style="margin-right: 10px;"><i class="ph-pencil"></i></a>
                                    <form action="{{ route('books.destroy',$book) }}" method="post">
                                        @csrf
                                        @method('DELETE')
                                        <button onclick="return confirm('Siz ushbu kitobni o\'chirmoqchimisiz?');"
                                                type="submit" class="btn btn-sm btn-danger"><i class="ph-trash"></i>
                                        </button>
                                    </form>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>

        <div class="card-footer">
            {{ $books->links() }}
        </div>
    </div>
@endsection