routes/web.php
<?php

use App\Http\Controllers\Announcements\AnnouncementController;
use App\Http\Controllers\Auth\AuthController;
use App\Http\Controllers\Books\BookController;
use App\Http\Controllers\Categories\CategoryController;
use App\Http\Controllers\Electrons\ElectronController;
use App\Http\Controllers\Genres\GenreController;
use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Route::get('/', [AuthController::class, 'login'])->name('login');
Route::post('/login', [AuthController::class, 'auth'])->name('auth.login');
Route::get('/logout', [AuthController::class, 'logout'])->name('auth.logout');

//---------------------------------------------------------------  ADMIN START -------------------------------------------------------------------------------------------------
Route::group(['prefix' => 'dashboard', 'middleware' => ['auth:sanctum']], function () {
    Route::get('index', [HomeController::class, 'index'])->name('admin.home');
    Route::resource('categories', CategoryController::class);
    Route::resource('genres', GenreController::class);
    Route::resource('books', BookController::class);
    Route::resource('electrons', ElectronController::class);
    Route::resource('announcements', AnnouncementController::class);
});
//---------------------------------------------------------------  ADMIN END -----------------------------------------------------------------------------------------------------

resources/views/dashboard/partials/footer.blade.php
<div class="navbar navbar-sm navbar-footer border-top">
    <div class="container-fluid">
        <span>&copy; 2022 - {{ date('Y') }} <a target="_blank" href="https://buxdu.uz">BuxDU UZ</a></span>

        <ul class="nav">
{{--            <li class="nav-item">--}}
{{--                <a href="https://kopyov.ticksy.com/" class="navbar-nav-link navbar-nav-link-icon rounded" target="_blank">--}}
{{--                    <div class="d-flex align-items-center mx-md-1">--}}
{{--                        <i class="ph-lifebuoy"></i>--}}
{{--                        <span class="d-none d-md-inline-block ms-2">Support</span>--}}
{{--                    </div>--}}
{{--                </a>--}}
{{--            </li>--}}
{{--            <li class="nav-item ms-md-1">--}}
{{--                <a href="https://demo.interface.club/limitless/demo/Documentation/index.html" class="navbar-nav-link navbar-nav-link-icon rounded" target="_blank">--}}
{{--                    <div class="d-flex align-items-center mx-md-1">--}}
{{--                        <i class="ph-file-text"></i>--}}
{{--                        <span class="d-none d-md-inline-block ms-2">Docs</span>--}}
{{--                    </div>--}}
{{--                </a>--}}
{{--            </li>--}}
{{--            <li class="nav-item ms-md-1">--}}
{{--                <a href="https://themeforest.net/item/limitless-responsive-web-application-kit/13080328?ref=kopyov" class="navbar-nav-link navbar-nav-link-icon text-primary bg-primary bg-opacity-10 fw-semibold rounded" target="_blank">--}}
{{--                    <div class="d-flex align-items-center mx-md-1">--}}
{{--                        <i class="ph-shopping-cart"></i>--}}
{{--                        <span class="d-none d-md-inline-block ms-2">Purchase</span>--}}
{{--                    </div>--}}
{{--                </a>--}}
{{--            </li>--}}
        </ul>
    </div>
</div>

resources/views/dashboard/partials/navbar.blade.php
<div class="navbar navbar-dark navbar-expand-lg navbar-static border-bottom border-bottom-white border-opacity-10">
    <div class="container-fluid">
        <div class="d-flex d-lg-none me-2">
            <button type="button" class="navbar-toggler sidebar-mobile-main-toggle rounded-pill">
                <i class="ph-list"></i>
            </button>
        </div>

        <div class="navbar-brand flex-1 flex-lg-0">
            <a href="#" class="d-inline-flex align-items-center">
                <img src="{{ asset('dashboard/assets/images/logo_icon.svg')}}" alt="">
                <img src="{{ asset('dashboard/assets/images/logo_text_light.svg')}}" class="d-none d-sm-inline-block h-16px ms-3" alt="">
            </a>
        </div>

        <ul class="nav flex-row">
            <li class="nav-item d-lg-none">
                <a href="#navbar_search" class="navbar-nav-link navbar-nav-link-icon rounded-pill" data-bs-toggle="collapse">
                    <i class="ph-magnifying-glass"></i>
                </a>
            </li>
        </ul>

{{--        <div class="navbar-collapse justify-content-center flex-lg-1 order-2 order-lg-1 collapse" id="navbar_search">--}}
{{--            <div class="navbar-search flex-fill position-relative mt-2 mt-lg-0 mx-lg-3">--}}

{{--                <div class="dropdown-menu w-100 p-3">--}}
{{--                    <div class="d-flex align-items-center mb-3">--}}
{{--                        <h6 class="mb-0">Search options</h6>--}}
{{--                        <a href="#" class="text-body rounded-pill ms-auto">--}}
{{--                            <i class="ph-clock-counter-clockwise"></i>--}}
{{--                        </a>--}}
{{--                    </div>--}}

{{--                    <div class="mb-3">--}}
{{--                        <label class="d-block form-label">Category</label>--}}
{{--                        <label class="form-check form-check-inline">--}}
{{--                            <input type="checkbox" class="form-check-input" checked>--}}
{{--                            <span class="form-check-label">Invoices</span>--}}
{{--                        </label>--}}
{{--                        <label class="form-check form-check-inline">--}}
{{--                            <input type="checkbox" class="form-check-input">--}}
{{--                            <span class="form-check-label">Files</span>--}}
{{--                        </label>--}}
{{--                        <label class="form-check form-check-inline">--}}
{{--                            <input type="checkbox" class="form-check-input">--}}
{{--                            <span class="form-check-label">Users</span>--}}
{{--                        </label>--}}
{{--                    </div>--}}

{{--                    <div class="mb-3">--}}
{{--                        <label class="form-label">Addition</label>--}}
{{--                        <div class="input-group">--}}
{{--                            <select class="form-select w-auto flex-grow-0">--}}
{{--                                <option value="1" selected>has</option>--}}
{{--                                <option value="2">has not</option>--}}
{{--                            </select>--}}
{{--                            <input type="text" class="form-control" placeholder="Enter the word(s)">--}}
{{--                        </div>--}}
{{--                    </div>--}}

{{--                    <div class="mb-3">--}}
{{--                        <label class="form-label">Status</label>--}}
{{--                        <div class="input-group">--}}
{{--                            <select class="form-select w-auto flex-grow-0">--}}
{{--                                <option value="1" selected>is</option>--}}
{{--                                <option value="2">is not</option>--}}
{{--                            </select>--}}
{{--                            <select class="form-select">--}}
{{--                                <option value="1" selected>Active</option>--}}
{{--                                <option value="2">Inactive</option>--}}
{{--                                <option value="3">New</option>--}}
{{--                                <option value="4">Expired</option>--}}
{{--                                <option value="5">Pending</option>--}}
{{--                            </select>--}}
{{--                        </div>--}}
{{--                    </div>--}}

{{--                    <div class="d-flex">--}}
{{--                        <button type="button" class="btn btn-light">Reset</button>--}}

{{--                        <div class="ms-auto">--}}
{{--                            <button type="button" class="btn btn-light">Cancel</button>--}}
{{--                            <button type="button" class="btn btn-primary ms-2">Apply</button>--}}
{{--                        </div>--}}
{{--                    </div>--}}
{{--                </div>--}}
{{--            </div>--}}
{{--        </div>--}}

        <ul class="nav flex-row justify-content-end order-1 order-lg-2">
            <li class="nav-item ms-lg-2">
                <a href="#" class="navbar-nav-link navbar-nav-link-icon rounded-pill" data-bs-toggle="offcanvas" data-bs-target="#notifications">
                    <i class="ph-bell"></i>
                    <span class="badge bg-yellow text-black position-absolute top-0 end-0 translate-middle-top zindex-1 rounded-pill mt-1 me-1">2</span>
                </a>
            </li>

            <li class="nav-item nav-item-dropdown-lg dropdown ms-lg-2">
                <a href="#" class="navbar-nav-link align-items-center rounded-pill p-1" data-bs-toggle="dropdown">
                    <div class="status-indicator-container">
                        <img src="{{ asset('user.jpg') }}" class="w-32px h-32px rounded-pill" alt="">
                        <span class="status-indicator bg-success"></span>
                    </div>
                    <span class="d-none d-lg-inline-block mx-lg-2">{{ \Illuminate\Support\Facades\Auth::user()->name }}</span>
                </a>

                <div class="dropdown-menu dropdown-menu-end">
                    <a href="#" class="dropdown-item">
                        <i class="ph-user-circle me-2"></i>
                        My profile
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <i class="ph-gear me-2"></i>
                        Account settings
                    </a>
                    <a href="{{ route('auth.logout') }}" class="dropdown-item">
                        <i class="ph-sign-out me-2"></i>
                        Logout
                    </a>
                </div>
            </li>
        </ul>
    </div>
</div>

resources/views/dashboard/partials/sidebar.blade.php
<div class="sidebar sidebar-dark sidebar-main sidebar-expand-lg">

    <!-- Sidebar content -->
    <div class="sidebar-content">

        <!-- Sidebar header -->
        <div class="sidebar-section">
            <div class="sidebar-section-body d-flex justify-content-center">
                <h5 class="sidebar-resize-hide flex-grow-1 my-auto">Navigation</h5>

                <div>
                    <button type="button" class="btn btn-flat-white btn-icon btn-sm rounded-pill border-transparent sidebar-control sidebar-main-resize d-none d-lg-inline-flex">
                        <i class="ph-arrows-left-right"></i>
                    </button>

                    <button type="button" class="btn btn-flat-white btn-icon btn-sm rounded-pill border-transparent sidebar-mobile-main-toggle d-lg-none">
                        <i class="ph-x"></i>
                    </button>
                </div>
            </div>
        </div>
        <!-- /sidebar header -->


        <!-- Main navigation -->
        <div class="sidebar-section">
            <ul class="nav nav-sidebar" data-nav-type="accordion">

                <!-- Main -->
                <li class="nav-item-header pt-0">
                    <div class="text-uppercase fs-sm lh-sm opacity-50 sidebar-resize-hide">Main</div>
                    <i class="ph-dots-three sidebar-resize-show"></i>
                </li>

{{--                @if(\Illuminate\Support\Facades\Auth::user()->role_id == 1) {{--    ADMIN ROLE     --}}
                    <li class="nav-item">
                        <a href="{{ route('genres.index') }}" class="nav-link">
                            <i class="ph-article"></i>
                            <span>Janrlar ro'yxati</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ route('categories.index') }}" class="nav-link">
                            <i class="ph-list-bullets"></i>
                            <span>Kategoriyalar</span>
                        </a>
                    </li>

                <li class="nav-item">
                    <a href="{{ route('books.index') }}" class="nav-link">
                        <i class="ph-book"></i>
                        <span>Kitoblar</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('announcements.index') }}" class="nav-link">
                        <i class="ph-book"></i>
                        <span>Yangiliklar</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('electrons.index') }}" class="nav-link">
                        <i class="ph-book"></i>
                        <span>Elektron fayllar</span>
                    </a>
                </li>

{{--                    <li class="nav-item nav-item-submenu">--}}
{{--                        <a href="#" class="nav-link">--}}
{{--                            <i class="ph-users"></i>--}}
{{--                            <span>Kategoriyalar</span>--}}
{{--                        </a>--}}
{{--                        <ul class="nav-group-sub collapse">--}}
{{--                            <li class="nav-item">--}}
{{--                                <a href="{{ route('categ.index') }}" class="nav-link">Ichki formalar</a>--}}
{{--                            </li>--}}
{{--                            <li class="nav-item">--}}
{{--                                <a href="{{ route('external.index') }}" class="nav-link">Tashqi formalar</a>--}}
{{--                            </li>--}}
{{--                        </ul>--}}
{{--                    </li>--}}
{{--                @endif--}}
            </ul>
        </div>
        <!-- /main navigation -->

    </div>
    <!-- /sidebar content -->

</div>