routes/web.php
<?php

use App\Http\Controllers\Announcements\AnnouncementController;
use App\Http\Controllers\Auth\AuthController;
use App\Http\Controllers\Books\BookController;
use App\Http\Controllers\Categories\CategoryController;
use App\Http\Controllers\Electrons\ElectronController;
use App\Http\Controllers\Genres\GenreController;
use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Route::get('/', [AuthController::class, 'login'])->name('login');
Route::post('/login', [AuthController::class, 'auth'])->name('auth.login');
Route::get('/logout', [AuthController::class, 'logout'])->name('auth.logout');

//---------------------------------------------------------------  ADMIN START -------------------------------------------------------------------------------------------------
Route::group(['prefix' => 'dashboard', 'middleware' => ['auth:sanctum']], function () {
    Route::get('index', [HomeController::class, 'index'])->name('admin.home');
    Route::resource('categories', CategoryController::class);
    Route::resource('genres', GenreController::class);
    Route::resource('books', BookController::class);
    Route::resource('electrons', ElectronController::class);
    Route::resource('announcements', AnnouncementController::class);
});
//---------------------------------------------------------------  ADMIN END -----------------------------------------------------------------------------------------------------

app/Http/Controllers/Categories/CategoryController.php
<?php

namespace App\Http\Controllers\Categories;

use App\Domain\Categories\Actions\StoreCategoryAction;
use App\Domain\Categories\Actions\UpdateCategoryAction;
use App\Domain\Categories\DTO\StoreCategoryDTO;
use App\Domain\Categories\DTO\UpdateCategoryDTO;
use App\Domain\Categories\Models\Category;
use App\Domain\Categories\Repositories\CategoryRepository;
use App\Domain\Categories\Requests\StoreCategoryRequest;
use App\Domain\Categories\Requests\UpdateCategoryRequest;
use App\Http\Controllers\Controller;
use App\Http\Resources\Api\Categories\CategoryResource;
use Exception;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * @var mixed|CategoryRepository
     */
    public mixed $categories;

    /**
     * @param CategoryRepository $categoryRepository
     */
    public function __construct(CategoryRepository $categoryRepository)
    {
        $this->categories = $categoryRepository;
    }

    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        return view('dashboard.categories.index', [
            'categories' => $this->categories->paginate()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('dashboard.categories.create', [
            'categories' => $this->categories->getAllParentNull()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreCategoryRequest $request, StoreCategoryAction $action)
    {
        $request->validated();
        try {
            $dto = StoreCategoryDTO::fromArray($request->all());
            $action->execute($dto);
        } catch (Exception $exception) {
            return redirect()->back();
        }

        return redirect()->route('categories.index');
    }

    /**
     * Display the specified resource.
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Category $category)
    {
        return view('dashboard.categories.edit', [
            'categories' => $this->categories->getAllParentNull(),
            'category' => $category
        ]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateCategoryRequest $request, Category $category, UpdateCategoryAction $action)
    {
        $request->validated();
        $request->merge([
            'category' => $category
        ]);
        try {
            $dto = UpdateCategoryDTO::fromArray($request->all());
            $action->execute($dto);
        } catch (Exception $exception) {
            return redirect()->back();
        }

        return redirect()->route('categories.index');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Category $category)
    {
        $category->delete();

        return redirect()->back();
    }


//-----------------------------------------------------------------------------------------   API   ------------------------------------------------------------------------------

    public function getAllParentNullCategory()
    {
        return CategoryResource::collection($this->categories->getAllParentNull());
    }

//-----------------------------------------------------------------------------------------   API   ------------------------------------------------------------------------------
}

resources/views/dashboard/categories/create.blade.php
@extends('dashboard.layouts.master')
@section('content')
    <div class="card">
        <form action="{{ route('categories.store') }}" method="post" enctype="multipart/form-data">
            @csrf
            <div class="card-header">
                <h5 class="mb-0">Kategoriya qo'shish</h5>
                @if ($errors->any())
                    @foreach ($errors->all() as $error)
                        <div class="alert alert-danger">{{$error}}</div>
                    @endforeach
                @endif
            </div>

            <div class="card-body row">
                <div class="mb-3 col-md-12">
                    <label for="parent_id" class="form-label">Asosiy kategoriya <span class="text-danger fw-bold">(Majburiy emas!)</span></label>
                    <select class="form-control" name="parent_id" id="parent_id">
                        <option value="">Asosiy kategoriyani tanlang!</option>
                        @foreach($categories as $category)
                            <option value="{{ $category->id }}">{{ $category->name }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="mb-3 col-md-12">
                    <label for="name" class="form-label">Kategoriya nomi</label>
                    <input type="text" value="{{ old('name') }}" id="name" class="form-control" name="name" placeholder="Kategoriya nomi">
                </div>
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary w-100">Saqlash <i class="ph-paper-plane-tilt ms-2"></i>
                </button>
            </div>
        </form>
    </div>
@endsection

resources/views/dashboard/categories/edit.blade.php
@extends('dashboard.layouts.master')
@section('content')
    <div class="card">
        <form action="{{ route('categories.update',$category) }}" method="post" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="card-header">
                <h5 class="mb-0">Kategoriyani tahrirlash</h5>
                @if ($errors->any())
                    @foreach ($errors->all() as $error)
                        <div class="alert alert-danger">{{$error}}</div>
                    @endforeach
                @endif
            </div>

            <div class="card-body row">
                <div class="mb-3 col-md-12">
                    <label for="parent_id" class="form-label">Asosiy kategoriya <span class="text-danger fw-bold">(Majburiy emas!)</span></label>
                    <select class="form-control" name="parent_id" id="parent_id">
                        @foreach($categories as $ct)
                            @if($category->parent_id == $ct->id)
                                <option selected value="{{ $category->id }}">{{ $category->name }}</option>
                            @elseif($category->parent_id == null)
                                <option value="">Asosiy kategoriyani tanlang!</option>
                            @else
                                <option value="{{ $category->id }}">{{ $category->name }}</option>
                            @endif
                        @endforeach
                    </select>
                </div>

                <div class="mb-3 col-md-12">
                    <label for="name" class="form-label">Kategoriya nomi</label>
                    <input type="text" value="{{ $category->name }}" id="name" class="form-control" name="name"
                           placeholder="Kategoriya nomi">
                </div>
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary w-100">Saqlash <i class="ph-paper-plane-tilt ms-2"></i>
                </button>
            </div>
        </form>
    </div>
@endsection

resources/views/dashboard/categories/index.blade.php
@extends('dashboard.layouts.master')
@section('content')
    <div class="card">
        <div class="card-header d-flex align-content-center justify-content-between">
            <h5 class="mb-0">Kategoriyalar ro'yxati</h5>
            <div>
                <a href="{{ route('categories.create') }}" class="btn btn-sm btn-success">Qo'shish</a>
                <button type="button" class="btn btn-primary btn-sm">Filter</button>
            </div>
        </div>

        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>№</th>
                        <th>Kategoriya nomi</th>
                        <th>Harakat</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($categories as $category)
                        <tr>
                            <td>{{ ($categories->currentPage()-1)*$categories->perPage() + $loop->index+1 }}</td>
                            <td>{{ $category->name }}</td>
                            <td>
                                <div class="d-flex align-items-center">
                                    <a href="{{ route('categories.edit',$category) }}" class="btn btn-sm btn-info" style="margin-right: 10px;"><i class="ph-pencil"></i></a>
                                    <form action="{{ route('categories.destroy',$category) }}" method="post">
                                        @csrf
                                        @method('DELETE')
                                        <button onclick="return confirm('Siz ushbu kategoriyani o\'chirmoqchimisiz? (Agar bu asosiy kategoriya bo\'lsa bunga bog\'langan barcha sub kategoriyalar o\'chiriladi!!!)');" type="submit" class="btn btn-sm btn-danger"><i class="ph-trash"></i></button>
                                    </form>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>

        <div class="card-footer">
            {{ $categories->links() }}
        </div>
    </div>
@endsection